theme = "base16_terminal"

[editor]
auto-pairs = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
i = "move_char_right"
k = "insert_mode"
a = ["move_char_right", "insert_mode"]
n = "move_line_down"
e = "move_line_up"
j = "search_next"
S-j = "search_prev"
S-d = "delete_char_backward"
[keys.normal.g]
i = "goto_line_end"
n = "goto_last_line"
e = "goto_file_start"
g = "goto_line"
j = "no_op"
k = "no_op"
[keys.normal.v]
h = "move_char_left"
i = "move_char_right"
k = "insert_mode"
n = "move_line_down"
e = "move_line_up"
j = "search_next"
S-j = "search_prev"
[keys.normal.z]
n = "scroll_down"
e = "scroll_up"
j = "no_op"
k = "no_op"
