if [ -f ~/.profile ]; then
	source ~/.profile
fi

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt interactivecomments
# setopt appendhistory extendedglob
unsetopt beep
# bindkey -e
bindkey -v


zstyle :compinstall filename "~/.zshrc"
autoload -Uz compinit
compinit

# prompt (i would like to apologize to my future self)
# this unholy order is because of base16 colors
# TODO maybe detect if base16 colors is a thing and if not use the regular order
promptcolors=("1" "9" "3" "2" "6" "4" "5" "14")
# apparently arrays are 1-indexed what the fuck?
coloruser=${promptcolors[$(( (RANDOM % 8) + 1 ))]}
colorhost=${promptcolors[$(( (RANDOM % 8) + 1 ))]}
while [[ $coloruser == $colorhost ]]
do # this is quite bad
    colorhost=${promptcolors[$(( (RANDOM % 8) + 1 ))]}
done

PROMPT="
%F{${coloruser}}%n%f%F{7}@%f%F{${colorhost}}%m%f %F{15}%~%f
%# "
unset promptcolors
unset coloruser
unset colorhost

# aliases
if [ ${LS_COLORS?} ] ; then
    alias ls="ls --color=always"
fi
# TODO this is currently only doing color escape codes, figure out if it
# should do all escape codes with "less -r"
# TODO this is probably gonna break on busybox huh
alias la="ls -A"
alias ll="ls -lAh"
alias lsl="ls -lAh | less"
alias odx="od -t x1z"
alias asdf="setxkbmap us colemak"

# functions
function reboot-to-windows {
    WINDOWS_TITLE=`sudo grep -i 'windows' /boot/grub/grub.cfg|cut -d"'" -f2`
    sudo grub-reboot "$WINDOWS_TITLE"
    sudo reboot
}

function mkcd {
	mkdir -p $1 && cd $1
}
