if [ -f ~/.profile ]; then
	source ~/.profile
fi

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt interactivecomments
# setopt appendhistory extendedglob
unsetopt beep
#bindkey -e


zstyle :compinstall filename '/home/mew/.zshrc'
autoload -Uz compinit
compinit

# prompt
PROMPT="
%F{5}%n%f%F{7}@%f%F{4}%m%f %F{15}%~%f
%# "

# aliases
#alias ls="ls --color=auto"
alias la="ls -A"
alias ll="ls -lAh"
alias lsl="ls -lAh | less"
alias odx="od -t x1z"
alias asdf="setxkbmap us colemak"

# functions
function reboot-to-windows {
    WINDOWS_TITLE=`sudo grep -i 'windows' /boot/grub/grub.cfg|cut -d"'" -f2`
    sudo grub-reboot "$WINDOWS_TITLE"
    sudo reboot
}

function mkcd {
	mkdir -p $1 && cd $1
}

function build_deps {
	cd ~/aports
	for i in $(ap recursdeps $@ | xargs ap builddirs); do
    	cd */$i
    	abuild -i || break
	done
}


