[[language]]
name = "peg"
scope = "source.peg"
file-types = ["peg"]
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "zig"
rulers = [100]
text-width = 100

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    "}
